version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - mynetwork

  webserver:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456789'
      MYSQL_DATABASE: PetcareV2
      MYSQL_USER: nam
      MYSQL_PASSWORD: '123456789'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      #nếu muốn truy cập theo quyền admin thì dùng root
      PMA_USER: root
      #nếu muốn truy cập theo quyền user thì dùng user
      # PMA_USER: user
      PMA_PASSWORD: '123456789'
    depends_on:
      - db
    networks:
      - mynetwork  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data: {}

#docker-compose up -d
#docker-compose down
#docker exec -it <name> bash : truy cập vào bash của container
